[project]
name = "bg-gen"
version = "0.1.0"
description = "simple image generator for backgrounds"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pillow>=11.1.0",
    "rich>=13.9.4",
]
